[server]
host = "127.0.0.1"
port = 7733
# Optional auth token
# token = ""

[dragonite]
endpoint = "http://127.0.0.1:7272/scout/v2"

[filter]
# Expr syntax (expr-lang.org)
expression = "iv == 100 || great_rank <= 5 || ultra_rank <= 5 || iv == 0 || pokemon_id == 201"
